const configStyle = {
  container: {
    alignItems: "center",
    marginTop: 30,
  },
  accueilScreenContainer: {
    flex: 1,
    alignItems: "center",
    // backgroundColor: "white",
    justifyContent: "space-between",
    textAlign: "center",

    paddingBottom: 30,
    backgroundColor: "#9CC5A1",
  },
  //aussi utilisé pour le challengeScreen
  signUpScreenContainer: {
    flex: 1,
    textAlign: "center",
    alignItems: "center",
    padding: 25,
  },
  //aussi utilisé pour le kidProfilScreen et le confirmationCodeScreen (changer de nom)
  signInScreenContainer: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "white",
    justifyContent: "space-between",
    paddingTop: 50,
    paddingBottom: 30,
  },
  challengeScreenContainer: {
    flex: 1,
    textAlign: "center",
    alignItems: "center",
    padding: 25,
  },
  containerForm: {
    backgroundColor: "#9CC5A1",
    alignItems: "center",
    justifyContent: "center",
    width: 290,
    height: 200,
    borderRadius: 20,
  },
  kidProfilScreenContainerForm: {
    backgroundColor: "#9CC5A1",
    alignItems: "center",
    justifyContent: "center",
    width: 290,
    height: 250,
    borderRadius: 20,
  },
  image: {
    width: "100%",
    borderBottomLeftRadius: 100,
  },
  h1: {
    padding: 30,
    textAlign: "center",
    fontFamily: "Lato_700Bold",
    fontSize: 22,
    color: "white",
  },
  header: {
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  card: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    height: 75,
    backgroundColor: "white",
    borderRadius: 15,
    paddingLeft: 16,
    paddingRight: 14,
    marginTop: 15,
    marginBottom: 20,
    marginLeft: 16,
    marginRight: 16,
  },
  dashboardScreenCard: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "white",
    borderRadius: 15,
    paddingLeft: 16,
    paddingRight: 14,
    marginTop: 15,
    marginBottom: 20,
    marginLeft: 16,
    marginRight: 16,
  },
  trashbutton: {
    height: 25,
    width: 25,
    borderRadius: 50,
    backgroundColor: "grey",
  },
  dropdowncontainer: {
    paddingLeft: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
  },
  dropdown: {
    marginTop: 15,
    marginBottom: 15,
    height: 50,
    width: "70%",
    backgroundColor: "white",
    borderRadius: 12,
    padding: 12,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,

    elevation: 2,
  },
  error: {
    color: "red",
    textAlign: "center",
    fontFamily: "Lato_400Regular",
    fontSize: 15,
    marginTop: 10,
  },
  icon: {
    marginRight: 5,
  },
  item: {
    padding: 17,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  textItem: {
    flex: 1,
    fontSize: 16,
  },
  placeholderStyle: {
    fontSize: 16,
  },
  selectedTextStyle: {
    fontSize: 16,
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  inputSearchStyle: {
    display: "none",
  },
  buttonDisplay: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  notionButton: {
    color: "white",
    backgroundColor: "#FABE6D",
    padding: 8,
    marginRight: 10,
    marginBottom: 10,
  },
  button1: {
    width: 190,
    color: "white",
    backgroundColor: "#49A078",
    padding: 15,
    marginRight: 10,
    marginBottom: 10,
    borderRadius: 20,
  },
  button2: {
    width: 190,
    color: "white",
    backgroundColor: "#FFC9B9",
    padding: 15,
    marginRight: 10,
    marginBottom: 10,
    borderRadius: 20,
  },
  buttonList: {
    width: 40,
    color: "white",
    backgroundColor: "#FFC9B9",
    padding: 10,
    marginRight: 10,
    marginBottom: 10,
    borderRadius: 100,
  },
  buttonFonts: {
    color: "white",
    textAlign: "center",
    fontSize: 15,
    fontWeight: "bold",
  },
  inputList: {
    width: 300,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    padding: 10,
    fontSize: 15,
  },
  inputShare: {
    fontSize: 15,
  },
  input: {
    width: 300,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    padding: 10,
  },
  words: {
    flexDirection: "row",
    alignItems: "center",
  },
  text: {
    fontSize: 15,
    paddingTop: 10,
    paddingRight: 5,
    paddingLeft: 10,
  },
  //aussi utilisé pour confirmationCodeScreen (nom à changer)
  kidProfilScreenText: {
    textAlign: "center",
    fontFamily: "Lato_400Regular",
    marginBottom: 20,
    padding: 20,
    fontSize: 15,
  },
  signUpScreenText: {
    textAlign: "center",
    fontFamily: "Lato_400Regular",
    marginBottom: 20,
    padding: 20,
    fontSize: 15,
  },
  wordsListItem: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  titleH1: {
    textAlign: "center",
    marginTop: 10,
    marginBottom: 8,
    fontFamily: "Lato_400Regular",
    fontSize: 25,
  },
  title: {
    marginTop: 10,
    fontSize: 15,
    fontFamily: "Lato_700Bold",
    textAlign: "center",
  },
  textH6: {
    fontSize: 17,
    textAlign: "center",
  },
  fonts: {
    marginTop: 10,
    marginBottom: 20,
    textAlign: "center",
  },
  //pour le suivant : Aussi utilisé pour les écrans signIn et kidprofil et confirmationCodeScreen (nom à changer)
  signUpScreenFonts: {
    color: "white",
    textAlign: "center",
    fontSize: 18,
    fontWeight: "bold",
  },
  accueilScreenFonts: {
    color: "white",
    textAlign: "center",
    fontSize: 18,
    fontWeight: "bold",
  },
  //Pas sûre que ce soit utile. Rien ne change quand je le supprime
  notionName: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  //Idem, je ne vois pas à quoi ça sert
  notionNameDisplay: {
    padding: 10,
    width: 270,
  },
  //Idem, je ne vois pas à quoi ça sert
  notionText: {
    fontSize: 15,
  },
  funfact: {
    fontFamily: "Lato_400Regular",
    color: "black",
    marginHorizontal: 20,
    marginVertical: 20,
  },
  upperView: {
    backgroundColor: "#A6CFAB",
    borderRadius: 25,
    marginBottom: 10,
  },
  questionNumber: {
    display: "flex",
    flexDirection: "row",
    backgroundColor: "#216869",
    width: "100%",
    alignItems: "center",
    height: 50,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
  },
  titleDash: {
    textAlign: "center",
    marginTop: 10,
    marginBottom: 8,
    fontFamily: "Lato_400Regular",
    fontSize: 25,
  },
};

export default configStyle;
